language: node_js
node_js: 12

before_install:
  - npm install -g @lhci/cli@0.3.x

install:
  - npm ci

script:
  - npm run build
  - lhci autorun

addons:
  chrome: stable

cache: npm

notifications:
  email: false