name: Markdown Date Updater

on:
  push:
    paths:
      - "content/posts/**/*.md"
      - "content/tags/**/*.md"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Download InkoHX/blog-date-updater
        run: wget https://raw.githubusercontent.com/InkoHX/blog-date-updater/master/dist/index.js -O ./updater.js
      - name: Update Markdown file creation and modification dates
        run: node ./updater.js
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add content
          git commit -m "content: update modifiedDate & createdDate"
      - name: Push this repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
